- hosts: eos
  gather_facts: false

  tasks:
    - name: create management ssh acls
      arista.eos.eos_acls:
        config: '{{ eos_acls }}'
        state: merged
      register: _result
      changed_when: _result.commands != []

# use 'line' option instead of 'src' option, because it's mutually exclusive with 'match' option
    - name: modify others (non-resource-module)
      arista.eos.eos_config:
        lines: '{{ lookup("template", "eos_base_config.j2") | split("\n") }}'
        match: strict
